[2025-03-30T23:34:34.129+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T23:34:34.192+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_books_to_database.load_books_to_sql manual__2025-03-30T23:34:30.387447+00:00 [queued]>
[2025-03-30T23:34:34.222+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_books_to_database.load_books_to_sql manual__2025-03-30T23:34:30.387447+00:00 [queued]>
[2025-03-30T23:34:34.225+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-30T23:34:34.274+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_books_to_sql> on 2025-03-30 23:34:30.387447+00:00
[2025-03-30T23:34:34.291+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=215) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-30T23:34:34.298+0000] {standard_task_runner.py:72} INFO - Started process 216 to run task
[2025-03-30T23:34:34.298+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'import_books_to_database', 'load_books_to_sql', 'manual__2025-03-30T23:34:30.387447+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/etl_books.py', '--cfg-path', '/tmp/tmpik2oatam']
[2025-03-30T23:34:34.303+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask load_books_to_sql
[2025-03-30T23:34:34.499+0000] {task_command.py:467} INFO - Running <TaskInstance: import_books_to_database.load_books_to_sql manual__2025-03-30T23:34:30.387447+00:00 [running]> on host dd1836f126a3
[2025-03-30T23:34:34.771+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='azizjon' AIRFLOW_CTX_DAG_ID='import_books_to_database' AIRFLOW_CTX_TASK_ID='load_books_to_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T23:34:30.387447+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T23:34:30.387447+00:00'
[2025-03-30T23:34:34.774+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-30T23:34:34.868+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2025-03-30T23:35:02.589+0000] {logging_mixin.py:190} INFO - 
=== MALFORMED ROWS SKIPPED ===
[2025-03-30T23:35:02.591+0000] {logging_mixin.py:190} INFO - Line 209540: ['078946697X', 'DK Readers: Creating the X-Men, How It All Began (Level 4: Proficient Readers)\\";Michael Teitelbaum"', '2000', 'DK Publishing Inc', 'http://images.amazon.com/images/P/078946697X.01.THUMBZZZ.jpg', 'http://images.amazon.com/images/P/078946697X.01.MZZZZZZZ.jpg', 'http://images.amazon.com/images/P/078946697X.01.LZZZZZZZ.jpg', ''] | Error: invalid literal for int() with base 10: 'DK Publishing Inc'
[2025-03-30T23:35:02.593+0000] {logging_mixin.py:190} INFO - Line 220733: ['2070426769', 'Peuple du ciel, suivi de \'Les Bergers\\";Jean-Marie Gustave Le ClÃ?Â©zio"', '2003', 'Gallimard', 'http://images.amazon.com/images/P/2070426769.01.THUMBZZZ.jpg', 'http://images.amazon.com/images/P/2070426769.01.MZZZZZZZ.jpg', 'http://images.amazon.com/images/P/2070426769.01.LZZZZZZZ.jpg', ''] | Error: invalid literal for int() with base 10: 'Gallimard'
[2025-03-30T23:35:02.595+0000] {logging_mixin.py:190} INFO - Line 221680: ['0789466953', 'DK Readers: Creating the X-Men, How Comic Books Come to Life (Level 4: Proficient Readers)\\";James Buckley"', '2000', 'DK Publishing Inc', 'http://images.amazon.com/images/P/0789466953.01.THUMBZZZ.jpg', 'http://images.amazon.com/images/P/0789466953.01.MZZZZZZZ.jpg', 'http://images.amazon.com/images/P/0789466953.01.LZZZZZZZ.jpg', ''] | Error: invalid literal for int() with base 10: 'DK Publishing Inc'
[2025-03-30T23:35:02.598+0000] {logging_mixin.py:190} INFO - 
Total bad rows: 3
[2025-03-30T23:35:02.608+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-30T23:35:02.660+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-30T23:35:02.662+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=import_books_to_database, task_id=load_books_to_sql, run_id=manual__2025-03-30T23:34:30.387447+00:00, execution_date=20250330T233430, start_date=20250330T233434, end_date=20250330T233502
[2025-03-30T23:35:02.778+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-30T23:35:02.849+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T23:35:02.856+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
